### PR TITLE
Update ibom.css

### PR DESCRIPTION
**Pull request by kirk-loeten**
The color was very light. This change has more contrast.

### CODE REVIEW

**Comment by kirk-loeten** [comment]
Sample of the used colors:
sample_notDark
sample_Dark

**Comment by qu1ck** [comment]
Track colors are light intentionally to not distract from silkscreen.
You can put your colors in user.css see customization section in wiki, I made it exactly so that everyone can style the page as they like because colors are subjective.

**Comment by kirk-loeten** [comment]
Yesterday I downloaded the last release (v2.3) in wiki. It is from Dez. 2019. The file ibom.py miss the user.css line and ignore the user.css. Now I work with the ibom.css local.

**Comment by qu1ck** [comment]
Yeah, to be able to use customization features you need to get latest from
master branch, it's not released yet.

**Pull request closed without merging**
