### PR TITLE
Changes to make it work on Python 3 with wxPython 4.

### PR DESCRIPTION
**Pull request by FabianInostroza**
Tested only on Linux, using KiCad with Python 2/wxPython 3 and KiCad with Python 3/wxPython 4

### CODE REVIEW

**Comment by qu1ck** [comment]
This looks great, thanks. I was planning to do this at some point, didn't expect it to be so easy.
I'll test this on windows and osx in a bit and merge if there are no issues.

**Comment by qu1ck** [comment]
This breaks cli usage:
```
Traceback (most recent call last):
  File "D:/OSP/KicadBomPlugin/InteractiveHtmlBom/generate_interactive_bom.py", line 12, in <module>
    from . import dialog
ValueError: Attempted relative import in non-package
```
Isn't python great? :-/
I don't see a way of fixing this without moving entry point of cli script outside of the package, which I'm reluctant to do because people are already used to this.

**Comment by FabianInostroza** [comment]
mm, that's bad, I didn't test for CLI usage.
What about adapting the module to use as `python -m InteractiveHtmlBom boardfile.kicad_pcb`?

**Comment by qu1ck** [comment]
I found a way to work around the limitation of python import system without moving the script itself. It may be not pretty but oh well. Maybe later I will reorganize directory structure and get rid of the hack.

**Pull request merged**
