### PR TITLE
Get part numbers from KiCAD BOM

### PR DESCRIPTION
**Pull request by drid**
Get part numbers from XML BOM generated by EESCHEMA

### CODE REVIEW

**Comment by qu1ck** [comment]
This looks great, thank you!
I will test this later and comment if I find any issues but here are few things that I found from cursory look at the diff.

1. There is no need to pass filename, pcb.GetFileName() returns the same thing.
2. Check for xml file's existence before calling parsing method. The catch block in that method is too wide.
3. If possible don't display part number column if none of the parts have it specified. Most hobbyists probably don't bother with specifying it and it will be wasting space. If you are not comfy with js I can take care of it later.

Also ideally there should be a command line flag that will let you specify the field name for "part number" to search for in xml.
Current default is fine but I think people use different fields like "MPN" "PN" "Part #" or whatever.

**Comment by qu1ck** [comment]
Ok, I've played with this and it works but it is not good user experience.

Main issue is that to generate the xml I have to first generate some other bom. With a plugin in eeschema which does not say that it will generate xml, but will generate something else.
I have no idea why there is no tool to just generate xml. But there is one to generate netlist file, which is neat s-expr format and has all the information including custom fields.

I think better strategy is to read netlist file. Most people generate it anyway and there is no need to muck around with eeschema bom plugins to get xml and a bom, neither of which you need.

The other issue is that really everyone uses different custom field for part number. If it's not configurable than only that 2% of users will be able to use this functionality, who happen to give the part number field the same default we will choose.

This is why I was putting this feature off until v2, which will have UI and ability to choose custom field names. Without at least command line flag to choose it, this feature is unusable for most because no-one will modify all their libraries and projects to change mpn field to "Part Number".

**Comment by Sembazuru** [comment]
"I think better strategy is to read netlist file."
Unfortunately, the "Update PCB from Schematic..." feature to pull directly from the schematic file instead of using a netlist means less netlists being generated. Though... I wonder if the functions to pull schematic data in PCBNew are exposed in the Python interface...

**Comment by qu1ck** [comment]
> Just hit generate and the file will appear in the project folder.
That is so not obvious.

I am still undecided. Either go with this approach or parse netlist or bite the bullet and parse schematic files themselves. In the latter case I'll have to support current and future file format and also there is much more headache with nested sheets etc.
Man, I wish eeschema had python interface.

**Comment by anderwm** [comment]
This worked great for me, but I am used to having the xml BOM file around because I use [kicost](https://github.com/xesscorp/KiCost) to do the costing of a board. There are some places where your project and theirs overlap so you might check it out. It was developed before there was a python interface so it does all of its grouping and work from the xml BOM.

**Comment by qu1ck** [comment]
Latest rev now supports pulling extra fields from both xml and netlist files.
@drid thanks for the contribution, I used some of your ideas in my implementation.

**Pull request closed without merging**
