### PR TITLE
Added keyboard shortcuts ArrowRight and ArrowLeft for checkbox `placed`

### PR DESCRIPTION
**Pull request by instalator**

### CODE REVIEW

**Comment by qu1ck** [comment]
I don't think this action needs another shortcut. There is already alt+number and "n" shortcut.

**Comment by instalator** [comment]
Installing and removing the checkbox is much more convenient using the arrows.

**Comment by qu1ck** [comment]
That's subjective. And it's completely unintuitive why "placed" is controlled by arrows as a special case. Or why marking as checked advances the row while marking unchecked doesn't.

This kind of customization is good use case for user.js.

**Comment by instalator** [comment]
When you install 200+ components and 100+ boards it saves a lot of time due to convenience. No problem, I'll be forked.

**Pull request closed without merging**
