### PR TITLE
Add CSV/TXT export according to #289

### PR DESCRIPTION
**Pull request by mhorsche**
Similar to #289

- Used copyToClipboard and saveFile due to duplicate code
- Text is escaped by double-quoted characters 
- Added pair of double-quoted characters

### CODE REVIEW

**Comment by qu1ck** [comment]
This looks much cleaner. Just a couple minor comments inline.

**Comment by mhorsche** [comment]
> This looks much cleaner. Just a couple minor comments inline.

If you don't like inline comments I will remove them ofc :wink:
This feature is awesome to generate a BOM for single layer fabrication eg. JLCPCB. No need to go through all parts for both sides.

**Comment by qu1ck** [comment]
By inline comments I mean github code review comments that I left on the diff.

**Comment by mhorsche** [comment]
> By inline comments I mean github code review comments that I left on the diff.

Sorry for being stupid but I could not see any comments, maybe you could help me?

**Comment by qu1ck** [comment]
> Sorry for being stupid but I could not see any comments, maybe you could help me?

Ugh, it was me being stupid, forgot to click submit on the review.

**Comment by qu1ck** [comment]
Looks good, thanks!

**Pull request merged**
