### PR TITLE
Deleted Chinese language

### PR DESCRIPTION
**Pull request by scarrrr316**
too many bugs when bat file run with  Chinese ， so I decided to delete it

### CODE REVIEW

**Comment by qu1ck** [comment]
Can you describe the bugs? I'd rather fix it then delete things.

**Comment by scarrrr316** [comment]
> Can you describe the bugs? I'd rather fix it then delete things.

some interesting bugs，it cant display Chinese normally，I dont know why .

**Comment by scarrrr316** [comment]
image

**Comment by scarrrr316** [comment]
how do you think

**Comment by qu1ck** [comment]
Didn't have time to test this and look into fixes yet

**Comment by scarrrr316** [comment]
emmmm，I believe that most of the Chinese user can understand those English sentences in batch file

**Comment by taotieren** [comment]
Because Chinese Windows uses GBK coding. 
Need to use `chcp utf-8/65001` for conversion. 
But when you output Chinese, you need to use `chcp gbk/936`.

**Pull request merged**
