### PR TITLE
New icon propose

### PR DESCRIPTION
**Pull request by hildogjr**
New icon propose: the transistor in both side represents the tags of the HTML language trying to appear like

< iBOM >

If don't fit well yet, I hope it could be consider for future designs.

### CODE REVIEW

**Comment by qu1ck** [comment]
I like the idea but after I tried how this looks I think features are too small to even make out that those are transistors. The vertical lines of the "base" merge with the button boundaries and emitter triangles become weird shaped blobs.

img

I think 32x32 pixels is very constraining so it will be hard to do any meaningful graphics there.
But thanks for suggestion, I agree that current icon is bad :)

**Comment by easyw** [comment]
Hi @qu1ck 
I think a checklist icon could do the job...
https://www.svgrepo.com/vectors/checklist/
https://openclipart.org/search/?query=checklist
two of them for example:

**Comment by qu1ck** [comment]
I think checklist alone does not represent the main functionality at all.
What do you think of this icon? Added the contrasting green for visibility and it's recognizable since it's been in the plugin html page since the beginning.

Imgur

**Comment by hildogjr** [comment]
Nice. Glace to see that I "simple" icon is take serious to represent the software (I did once to [KiCost](https://github.com/xesscorp/KiCost/blob/master/kicost/kicost.ico) thinking like this).

I have a propose, merging the 2 ideas:
icon
The left size became a checklist
The right side receive some "brake" to represent that is possible see just top, just both, both or neither.

The color is nice, @qu1ck. I think math also with dark themes in the KiCad GUI.

**Comment by hildogjr** [comment]
If KiCad support transparency in the icon, could be used this:
icon

**Comment by qu1ck** [comment]
You must have really sharp eyesight  :)
That's great but for average people on average screen 1px wide features are just indiscernible. These icons are magnified here on github, they look smaller in pcbnew.

Transparency is supported but I left the bezel around the border on purpose, without it black border disappears on dark themes. Corners can be rounded though.

**Comment by hildogjr** [comment]
True, about the the dark theme!
Take my other suggestions, if you like them. I agree with the icon general idea. :-D

**Comment by hildogjr** [comment]
One this just came to me:
icon
The contour just appear "IB" (IBOM ?) in this icon. :-P

**Comment by hildogjr** [comment]
icon
I tried a more "iB" approach.

**Comment by qu1ck** [comment]
I really like this last idea.
Some minor tweaks:
* the square cutout in the "B" part doesn't quite flow, I think rounded as in the shape of letter B is better.
* to bring out the iB more the F and B could be made a lighter shade
* pixel alignment or at least more uniform line widths would help
* rounded corners of the bezel with transparency

Also I do my icons in vector format now (svg) to be able to rescale them easily when need arises. If you are up to it, inkscape gets the job done, otherwise I will take care of it including my suggestions later today.

**Comment by hildogjr** [comment]
@qu1ck, I totally agree with ours addendum.
If you don't mind. Please, do the new icon. I am not good with images as with idea. Just check the example of the other KiCad plugin that I help to develop:
kicost
It not even vetorized.

**Comment by qu1ck** [comment]
I just pushed new icon. Thanks @hildogjr !

**Pull request closed without merging**
