### PR TITLE
Added language option

### PR DESCRIPTION
**Pull request by scarrrr316**
supported language：Chinese and English

change language method：edit bat file and input the language code ：English→en ，Chinese→zh

Why ？ There are Chines version of EasyEDA called LCEDA ，2 editor are  same except the server（I think）So I added Chinese for Chinese User

### CODE REVIEW

**Comment by scarrrr316** [comment]
I also want to know how can I edit github wiki of this project？
I want to add some explanation ，thx

**Comment by qu1ck** [comment]
Sorry, I don't know Chinese so will not be able to maintain this. And I can't check in files that I won't be able to edit.

Regarding wiki let me know what you want to add and I will update the wiki after basic editing.

**Comment by scarrrr316** [comment]
emmmmm，you dont need  to understand those chinese words/sentences，main program are same.

**Comment by qu1ck** [comment]
They are now but when I need to make changes I won't be able to make them to Chinese version.
Right way to do it is to decouple translation strings from the code. In that case when I need to make changes I will just add untranslated strings to Chinese strings file. If you can do it like that I will accept the pull request.
For an example of what I mean look at how translations are done in kicad installer
https://gitlab.com/kicad/packaging/kicad-win-builder/-/tree/master/nsis
There are separate files for translations and the code uses substitution variables. There should be a way to do something like that in bat file.

**Comment by scarrrr316** [comment]
I don't know whether it can do in bat file emmm
I think it should use python instead of batch

**Comment by qu1ck** [comment]
Bat files can import other bat files using `call another.bat`
If you declare translated strings as variables in another file which you import based on chosen language, it should work.

**Comment by scarrrr316** [comment]
Do like this ? ↓

```
if not defined pathofEDASourceFile (
if %language%==en (
	set /p pathofEDASourceFile=Please Drag the EasyEDA PCB source file here :
) else ( 
		set /p pathofEDASourceFile=请将您的EDA PCB源文件拖移至此:
) )


echo .
if %language%==en (
echo  Converting. . . . . . . . . .
) else (
echo  导出中. . . . . . . . . .
)
echo .

python %pyFilePath% %pathofEDASourceFile% %option%

if %language%==en (
set converted=EDA source file is converted to bom successfully!
) else (
 您的EDA 源文件已成功转换到 Bom ！
)
```

**Comment by qu1ck** [comment]
No what I mean is something like this.
You have 3 files:
```
translations\english.bat
translations\chinese.bat
run.bat
```

`english.bat` has contents like this
```
set intro_str="Hello"
set prompt_str="Drag file here"
...
```
`chinese.bat` has same variables but in Chinese
and `run.bat` is like this
```
if %language%==en {
  call translations\english.bat
} else {
  call translations\chinese.bat
}
...

echo %intro_str%
...
set /p pathofEDASourceFile=%prompt_str%
...
```

**Comment by scarrrr316** [comment]
oh，ok.......and I will also try to translate those dialog

**Comment by qu1ck** [comment]
If you do dialog translation make sure to test it with kicad and open a separate pull request for it.

**Comment by scarrrr316** [comment]
ok.....

**Pull request closed without merging**
