### PR TITLE
added allegro skill script

### PR DESCRIPTION
**Pull request by juulsA**
added a folder named `skill`, which includes all additional files to ( hopefully ) get the interactive bom working for allegro

### CODE REVIEW

**Comment by qu1ck** [comment]
Looks like I completely misunderstood what you were doing. I was expecting a custom parser built into ibom like easyeda parser or the recently added eagle parser. What you got is much closer to previously provided eagle script (see [compatibility](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Compatibility) page in project wiki) that created an intermediary json that was then parsed by ibom but you are skipping the ibom part and generating html directly.

There are few issues with this approach:
1. You are hardcoding all settings and asking user to change code if they want to tweak it. Not user friendly at all.
2. You are hardcoding font data to only ascii characters and that doesn't cover everyone's needs. Current newstroke font doesn't have full utf-8 coverage either but it covers most popular things.
3. You are asking me to merge a big chunk of code in a scripting language I don't know, can't test and will never learn because it's allegro's invention and is useless for anything else.

I suggest the following:
You restructure your script to output the json instead. See the [schema](https://github.com/openscopeproject/InteractiveHtmlBom/blob/master/InteractiveHtmlBom/ecad/schema/genericjsonpcbdata_v1.schema) for it, it mostly matches pcbdata that you are already outputing, you just have to remove all the html handling stuff. Then user can use existing ibom config dialog to tweak it how they want. There may be a patch needed to be able to use newstroke font data with json parser but we can figure it out.
Then you publish your script as a separate project, I will add information about it and links to the wiki so users know they can use ibom with allegro cad. Same as it used to be with eagle.

Your work is valuable and I'd hate to lose it, I just don't think that merging it into ibom source tree is the right approach. I'm sorry about the miscommunication mentioned above.

**Comment by juulsA** [comment]
No problem, this happens! 

1. yes you're right, I thought of providing a config file in the future 
2. yes, but allegro does not support utf-8 
3. I understand that!

I will take a look at it, but I can't promise, that I will provide a restructured code or it will take some time. I decided to go that way, because for me, this is the most comfortable way. When generating the pcb-files, this is only one step, which needs to be done by allegro. I also don't know, if there is anyone else than me, who is interested in an export from allegro to the interactive bom, as I think not many are using this tool ... so, is it worth the effort restructuring it ... nobody knows ... 

So maybe you're right, that the source tree is not the right place for this! But if anyone is interested, I will provided the script separately.
 
If you either merged it or not, I would have done this! So, nevermind! Thank you for your support so far; the interactive bom is a great tool!

**Comment by qu1ck** [comment]
I encourage you to do the last step of generating json because you are already 95% there. If your script can generate pcbdata to insert into html you can take that structure directly, add component table and that's it. The schema I linked is specifically designed to match what html side uses.

There is an example of json file [here](https://github.com/openscopeproject/InteractiveHtmlBom/pull/216#issuecomment-785063307) you will see that it's made almost entirely of pcbdata that you already generate.

If you decide to not work on it please let me know, I will link this MR in the wiki for someone else to see and maybe add the missing piece.

**Comment by juulsA** [comment]
Ok, if you say I'm 95% there, than I'll try do this! Let's see, what I can get done tomorrow ...

**Pull request closed without merging**
