### PR TITLE
Add checkbox to also export the BOM to csv

### PR DESCRIPTION
**Pull request by tytgatlieven**
This adds the functionality to also be able to export the current BOM to CSV.
This allows a nice bom csv, fully configurable by the InteractiveHtmlBom GUI

### CODE REVIEW

**Comment by tytgatlieven** [comment]
I just noticed that the last release includes a csv export function in the html web page.
The idea in this PR is to export it directly at the same time as the html.
Both can live simultaneously imo.

**Comment by qu1ck** [comment]
There's plenty of other bom generators that do csv like KiBom or even one included into kicad itself.
The value of save as csv feature in html is that it saves the bom table as it is displayed, i.e. with checkboxes and filtered rows.

The only thing this addition does is a bit of convenience to save a click. Not worth the config bloat IMO.

There's also other issues (fixable) that I'm mentioning for future reference:
1. Avoid copy paste. Refactor common code into a function. In your current implementation there are even unused variables as artifacts of copy paste.
2. Use wxFormBuilder to edit the GUI, don't edit the `dialog_base.py` directly.

I won't merge this but still, thanks for the interest to contribute.

**Comment by tytgatlieven** [comment]
Dear

Though I do agree there are already a number of alternatives, they are all really cumbersome to use.
All need upfront knowledge of the used fields in the script that is called, including the grouping. Which means syntax to be found out on every BOM creation. Assembly alternatives are truly a disaster. Moreover, this bom is installable through the plugin manager system.
And last but not least, I doubt a lot of people will find the button in the HTML version in case they are searching for export to CSV.

In my opinion InteractiveHTMLBOM could become the defacto BOM export plugin.

Hence: Would you reconsider this pull request?

I'm definitly willing to make the improvements/changes you mention. 

kind regards

Lieven

**Comment by qu1ck** [comment]
I agree that the csv save button is not the most easily discoverable, but then again, people looking for a csv bom would not think to install a plugin named interactive HTML bom.

This project is not intended to and can't be a universal jack of all trades bom generator. It is aimed at a specific use case first: easy to use documentation for manual assembly. Anything that doesn't directly improve that use case can only be added if it doesn't have any detriments. Config and UI bloat is one of such detriments I'm trying to avoid and the feature you are proposing doesn't provide enough value to counter that.

The argument about ibom being the easiest to use is a valid one (even if I tout my own horn here) but an obvious alternative would be to improve other bom generators. Have you looked into what would it take to add a UI to one of the powerful eeschema based scripts? I don't think it would be hard. You can even reuse code from this project, that's the power of open source.

**Pull request closed without merging**
