### PR TITLE
add new function to bat file

### PR DESCRIPTION
**Pull request by scarrrr316**
dont need to double-click that bat file
 new fuction : drag source file and open with run.bat  like this
image

### CODE REVIEW

**Comment by qu1ck** [comment]
Please rebase on top of master.

**Comment by scarrrr316** [comment]
emmmmm，sorry,I dont know what you mean

**Comment by qu1ck** [comment]
This pull request has conflicts with master branch of the repository, I can't merge it or review it because diff is not displayed correctly.
You need to do `git fetch origin` and `git pull -r origin/master` to rebase (replace origin with whatever the name of the remote is).

**Comment by scarrrr316** [comment]
emmmm，I am new to use the pull request function of github , you mean I need to create a new branch ， edit again and  pull requets again ,right?

**Comment by qu1ck** [comment]
That will work too but it's easier to just rebase using commands I wrote in previous post. After rebasing force push to your branch and the pull request will update automatically.

**Comment by scarrrr316** [comment]
emmmmm，I want to install github desktop but my storeage was full ，sucks

**Comment by scarrrr316** [comment]
I will pull it again after add translate and add new fuction

**Comment by scarrrr316** [comment]
image
why？！

**Comment by qu1ck** [comment]
Your branch is still 8 commits ahead and 1 behind which means it's still diverged. If you rebased locally you need to push to your fork.

**Pull request closed without merging**
