### PR TITLE
Update plugin svg from 32x32 px to 24x24 px

### PR DESCRIPTION
**Pull request by leoheck**

### CODE REVIEW

**Comment by qu1ck** [comment]
Can you regenerate InteractiveHtmlBom/icon.png ? That's the one that is rendered in toolbar.

I haven't done simple scaling so far because I'm afraid that the features that I pixel aligned for 32px will be blurry in 24px unless they are realigned and there may not be space to realign them so icon may have to be simplified.

**Comment by leoheck** [comment]
Sure. I've just scaled it down to since I was not sure what you wanted to do. I will regenerate the png, It is is not goog, we can fix it later, cool? Because 32px icon it is worst than a blurry one, I think.

**Comment by qu1ck** [comment]
I redid the icon, thanks for the PR still.

**Comment by leoheck** [comment]
No problem. Thanks for fixing to this.

**Pull request closed without merging**
